**ElasticNet Regresyon**

In [13]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn import model_selection
import matplotlib.pyplot as plt
from sklearn.linear_model import RidgeCV, LassoCV, ElasticNetCV

In [14]:
db = pd.read_csv("./dataset01.csv")
db = db.dropna()
dms = pd.get_dummies(db[['League', 'Division','NewLeague']])
y = db["Salary"]
X_ = db.drop (['Salary', 'League', 'Division', 'NewLeague'], axis = 1).astype('float64')
X = pd.concat([X_, dms[['League_N', 'Division_W', 'NewLeague_N']]], axis = 1)
X_train, X_test, y_train, y_test = train_test_split(X,
                                                   y,
                                                   test_size = 0.25,
                                                   random_state = 42)

In [15]:
X_train.head()

AtBat   Hits  HmRun  Runs   RBI  Walks  Years  CAtBat   CHits  CHmRun  \
183  328.0   91.0   12.0  51.0  43.0   33.0    2.0   342.0    94.0    12.0   
229  514.0  144.0    0.0  67.0  54.0   79.0    9.0  4739.0  1169.0    13.0   
286  593.0  152.0   23.0  69.0  75.0   53.0    6.0  2765.0   686.0   133.0   
102  233.0   49.0    2.0  41.0  23.0   18.0    8.0  1350.0   336.0     7.0   
153  341.0   95.0    6.0  48.0  42.0   20.0   10.0  2964.0   808.0    81.0   

     CRuns   CRBI  CWalks  PutOuts  Assists  Errors  League_N  Division_W  \
183   51.0   44.0    33.0    145.0     59.0     8.0         1           0   
229  583.0  374.0   528.0    229.0    453.0    15.0         1           0   
286  369.0  384.0   321.0    315.0     10.0     6.0         0           1   
102  166.0  122.0   106.0    102.0    132.0    10.0         0           0   
153  379.0  428.0   221.0    158.0      4.0     5.0         1           1   

     NewLeague_N  
183            1  
229            1  
286            0  
102            0  
153            1

In [7]:
enet_model = ElasticNet().fit(X_train, y_train)

/Users/mohammadqasemmuzafarzada/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.488e+06, tolerance: 3.899e+03
  model = cd_fast.enet_coordinate_descent(


In [8]:
enet_model.coef_

array([ -1.86256172,   8.70489065,   5.10426375,  -2.89875799,
        -1.28642985,   5.24343682,   6.04480276,  -0.14701495,
        -0.21566628,  -0.7897201 ,   1.80813117,   0.80914508,
        -0.61262382,   0.26816203,   0.27172387,  -0.36530729,
        19.2186222 , -31.16586592,   8.98369938])

In [9]:
enet_model.intercept_

-6.465955602112558

**Tahmin**

In [21]:
enet_model.predict(X_train)[0:9]

array([325.74706292, 776.06632333, 522.86508419, 107.64091955,
       449.03139566, 997.76095723,  99.78828622, 311.33763086,
       418.50335021])

In [22]:
enet_model.predict(X_test)[0:6]

array([ 577.79111731,  617.33202224, 1031.39113156,  364.95861575,
        489.51894393,  300.74185842])

In [23]:
y_pred = enet_model.predict(X_test)

In [24]:
np.sqrt(mean_squared_error(y_test, y_pred))

357.16765481812445

In [25]:
r2_score(y_test, y_pred)

0.4107022246932692